export const endpoint = {
  AUTH: "/auth",
  KELOLA_TRAINING: "/training",
  KELOLA_INSTRUKTUR_ASESOR: "/instruktur-or-asesor",
  MEDIA: "/media",
  JADWAL: "/schedule",
  DETAIL_JADWAL: "/detail-schedule",
  NOTIFY: "notify",
  SESSIONSCHEDULE: "/session-detail-schedule",
  CREDENTIAL: "/credential",
  SETPASSWORD: "/set-password",
  PARTICIPANT_IMPORT: "/participant-import",
  PARTICIPANT: "/participant",
  MATERI: "/materi",
  ASSESMENT: "/assesment",
  E_SERTIFIKAT: "/e-sertifikat",
  LAPORAN: "/laporan",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  SERTIFIKAT_VERIFY: "/sertifikat",
  MY_TRAINING: "/my-training",
  PENILAIAN: "/penilaian",
};
